import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";

export const identityKind = pgEnum("identity_kind", ["email", "phone"]);
export const resolutionState = pgEnum("resolution_state", ["resolved", "identity_conflict"]);
export const jobKind = pgEnum("job_kind", ["acknowledgment_email", "internal_notification", "zoho_lead_sync", "form2_invitation"]);
export const jobStatus = pgEnum("job_status", ["blocked", "pending", "running", "retry", "succeeded", "dead", "cancelled"]);
const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };
export const leads = pgTable("leads", { id: uuid("id").primaryKey().defaultRandom(), displayName: text("display_name").notNull(), firstName: text("first_name").notNull(), lastName: text("last_name").notNull(), zohoLeadId: text("zoho_lead_id").unique(), zohoSyncedAt: timestamp("zoho_synced_at", { withTimezone: true }), zohoSyncVersion: integer("zoho_sync_version").notNull().default(0), deletedAt: timestamp("deleted_at", { withTimezone: true }), ...timestamps });
export const enquiries = pgTable("enquiries", { id: uuid("id").primaryKey().defaultRandom(), submissionId: uuid("submission_id").notNull().unique(), payloadDigest: text("payload_digest").notNull(), leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }), resolutionState: resolutionState("resolution_state").notNull(), conflictingLeadIds: uuid("conflicting_lead_ids").array().notNull().default(sql`ARRAY[]::uuid[]`), rawFullName: text("raw_full_name"), rawEmail: text("raw_email"), rawPhone: text("raw_phone"), rawEnquiry: text("raw_enquiry"), normalizedFullName: text("normalized_full_name").notNull(), firstName: text("first_name").notNull(), lastName: text("last_name").notNull(), normalizedEmail: text("normalized_email").notNull(), normalizedPhone: text("normalized_phone").notNull(), countryCode: text("country_code").notNull().default("IN"), normalizedEnquiry: text("normalized_enquiry").notNull(), privacyNoticeVersion: text("privacy_notice_version").notNull(), consentedAt: timestamp("consented_at", { withTimezone: true }).notNull().defaultNow(), rawPurgeAfter: timestamp("raw_purge_after", { withTimezone: true }).notNull(), rawPurgedAt: timestamp("raw_purged_at", { withTimezone: true }), ...timestamps }, (t) => [index("enquiries_lead_idx").on(t.leadId), check("enquiries_resolution_consistency", sql`(${t.resolutionState} = 'resolved' AND ${t.leadId} IS NOT NULL AND cardinality(${t.conflictingLeadIds}) = 0) OR (${t.resolutionState} = 'identity_conflict' AND ${t.leadId} IS NULL AND cardinality(${t.conflictingLeadIds}) = 2)`)]);
export const leadIdentities = pgTable("lead_identities", { id: uuid("id").primaryKey().defaultRandom(), leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }), kind: identityKind("kind").notNull(), normalizedValue: text("normalized_value").notNull(), isCurrent: integer("is_current").notNull().default(1), firstSeenEnquiryId: uuid("first_seen_enquiry_id").references(() => enquiries.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("identity_global_unique").on(t.kind, t.normalizedValue), uniqueIndex("identity_current_per_kind").on(t.leadId, t.kind).where(sql`${t.isCurrent} = 1`), index("identity_lead_last_seen_idx").on(t.leadId, t.kind, t.lastSeenAt)]);
export const workflowJobs = pgTable("workflow_jobs", { id: uuid("id").primaryKey().defaultRandom(), enquiryId: uuid("enquiry_id").notNull().references(() => enquiries.id, { onDelete: "cascade" }), leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }), kind: jobKind("kind").notNull(), status: jobStatus("status").notNull(), dedupeKey: text("dedupe_key").notNull().unique(), prerequisiteJobId: uuid("prerequisite_job_id"), attemptCount: integer("attempt_count").notNull().default(0), maxAttempts: integer("max_attempts").notNull(), nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).notNull().defaultNow(), lockedAt: timestamp("locked_at", { withTimezone: true }), leaseExpiresAt: timestamp("lease_expires_at", { withTimezone: true }), lockedBy: uuid("locked_by"), providerRecordId: text("provider_record_id"), lastErrorCode: text("last_error_code"), lastErrorClass: text("last_error_class"), lastErrorAt: timestamp("last_error_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps }, (t) => [index("workflow_jobs_claim_idx").on(t.status, t.nextAttemptAt, t.createdAt), foreignKey({ columns: [t.prerequisiteJobId], foreignColumns: [t.id], name: "workflow_jobs_prerequisite_fk" }).onDelete("restrict")]);
export const form2Invites = pgTable("form2_invites", { id: uuid("id").primaryKey(), leadId: uuid("lead_id").notNull().references(() => leads.id, { onDelete: "cascade" }), enquiryId: uuid("enquiry_id").notNull().references(() => enquiries.id, { onDelete: "cascade" }), purpose: text("purpose").notNull().default("form2"), tokenVersion: integer("token_version").notNull().default(1), tokenHash: text("token_hash").notNull().unique(), encryptedVerifier: text("encrypted_verifier").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), sentAt: timestamp("sent_at", { withTimezone: true }), consumedAt: timestamp("consumed_at", { withTimezone: true }), revokedAt: timestamp("revoked_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [check("form2_invites_purpose_check", sql`${t.purpose} = 'form2'`), uniqueIndex("form2_invites_one_active_per_enquiry").on(t.enquiryId).where(sql`${t.consumedAt} IS NULL AND ${t.revokedAt} IS NULL`)]);
export const providerTokens = pgTable("provider_tokens", { provider: text("provider").primaryKey(), accessToken: text("access_token"), expiresAt: timestamp("expires_at", { withTimezone: true }), refreshLockedUntil: timestamp("refresh_locked_until", { withTimezone: true }), refreshAttemptedAt: timestamp("refresh_attempted_at", { withTimezone: true }), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(), metadata: jsonb("metadata") });
export const abuseCounters = pgTable("contact_abuse_counters", { bucket: text("bucket").primaryKey(), count: integer("count").notNull(), windowExpiresAt: timestamp("window_expires_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("abuse_counter_expiry_idx").on(t.windowExpiresAt)]);
