import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import { getSql } from "@/lib/db/client";
import { claimJobs, completeJob, failJob, releaseJobWithoutAttempt } from "./repository";
const enabled = Boolean(process.env.CONTACT_INTEGRATION_DATABASE_URL && process.env.RUN_CONTACT_INTEGRATION_TESTS === "true"); const describeDb = enabled ? describe : describe.skip; let sql: ReturnType<typeof getSql>;
const enquiryId = "10000000-0000-4000-8000-000000000001"; const leadId = "20000000-0000-4000-8000-000000000001";
async function seed(kind = "acknowledgment_email", status = "pending", prerequisite?: string) { const rows = await sql<{ id: string }[]>`INSERT INTO workflow_jobs (enquiry_id, lead_id, kind, status, max_attempts, prerequisite_job_id, dedupe_key) VALUES (${enquiryId}::uuid, ${leadId}::uuid, ${kind}::job_kind, ${status}::job_status, 8, ${prerequisite ?? null}::uuid, ${`test:${kind}:${crypto.randomUUID()}`}) RETURNING id`; return rows[0].id; }
describeDb("Postgres job lease integration", () => {
 beforeAll(() => { sql = getSql();  process.env.CONTACT_IDEMPOTENCY_SECRET = "integration-idempotency-secret"; });
 beforeEach(async () => { await sql`TRUNCATE workflow_jobs, form2_invites, lead_identities, enquiries, leads CASCADE`; await sql`INSERT INTO leads (id, display_name, first_name, last_name) VALUES (${leadId}::uuid, 'Asha Menon', 'Asha', 'Menon')`; await sql`INSERT INTO enquiries (id, submission_id, payload_digest, lead_id, resolution_state, conflicting_lead_ids, normalized_full_name, first_name, last_name, normalized_email, normalized_phone, normalized_enquiry, privacy_notice_version, raw_purge_after) VALUES (${enquiryId}::uuid, '30000000-0000-4000-8000-000000000001'::uuid, 'digest', ${leadId}::uuid, 'resolved', ARRAY[]::uuid[], 'Asha Menon', 'Asha', 'Menon', 'asha@example.com', '+919876543210', 'A detailed enquiry for a studio project.', 'v1', now() + interval '1 day')`; });
 it("makes overlapping claims exclusive", async () => { await seed(); const [one, two] = await Promise.all([claimJobs("40000000-0000-4000-8000-000000000001", 1, ["acknowledgment_email"]), claimJobs("40000000-0000-4000-8000-000000000002", 1, ["acknowledgment_email"])]); expect(one.length + two.length).toBe(1); });
 it("reclaims expired leases and rejects stale completion", async () => { await seed(); const [stale] = await claimJobs("40000000-0000-4000-8000-000000000001", 1, ["acknowledgment_email"]); await sql`UPDATE workflow_jobs SET lease_expires_at = now() - interval '1 second' WHERE id = ${stale.id}::uuid`; const [fresh] = await claimJobs("40000000-0000-4000-8000-000000000002", 1, ["acknowledgment_email"]); expect(fresh.id).toBe(stale.id); expect(await completeJob(stale)).toBe(false); expect(await completeJob(fresh)).toBe(true); });
 it("releases a budget-skipped claim without consuming an attempt", async () => { await seed(); const [claimed] = await claimJobs("40000000-0000-4000-8000-000000000001", 1, ["acknowledgment_email"]); await releaseJobWithoutAttempt(claimed); const rows = await sql<{ status: string; attempt_count: number }[]>`SELECT status, attempt_count FROM workflow_jobs WHERE id = ${claimed.id}::uuid`; expect(rows[0]).toEqual({ status: "pending", attempt_count: 0 }); });
 it("releases blocked invitation on Zoho success and cancels it on terminal Zoho failure", async () => { const zohoOne = await seed("zoho_lead_sync"); const inviteOne = await seed("form2_invitation", "blocked", zohoOne); const [claimedOne] = await claimJobs("40000000-0000-4000-8000-000000000001", 1, ["zoho_lead_sync"]); await completeJob(claimedOne, "zoho-1"); const released = await sql<{ status: string }[]>`SELECT status FROM workflow_jobs WHERE id = ${inviteOne}::uuid`; expect(released[0].status).toBe("pending"); const zohoTwo = await seed("zoho_lead_sync"); const inviteTwo = await seed("form2_invitation", "blocked", zohoTwo); const [claimedTwo] = await claimJobs("40000000-0000-4000-8000-000000000002", 1, ["zoho_lead_sync"]); expect(await failJob(claimedTwo, { code: "ZOHO_IDENTITY_CONFLICT", retryable: false })).toBe(true); const cancelled = await sql<{ status: string; last_error_code: string }[]>`SELECT status, last_error_code FROM workflow_jobs WHERE id = ${inviteTwo}::uuid`; expect(cancelled[0]).toEqual({ status: "cancelled", last_error_code: "ZOHO_DEPENDENCY_DEAD" }); });
});
