import { beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
const send = vi.fn();
vi.mock("resend", () => ({ Resend: class { emails = { send }; } }));
import { getSql } from "@/lib/db/client";
import { sendForm2Invitation } from "./invitations";
const enabled = Boolean(process.env.CONTACT_INTEGRATION_DATABASE_URL && process.env.RUN_CONTACT_INTEGRATION_TESTS === "true"); const describeDb = enabled ? describe : describe.skip; let sql: ReturnType<typeof getSql>;
const enquiryId = "50000000-0000-4000-8000-000000000001"; const leadId = "60000000-0000-4000-8000-000000000001";
describeDb("Form 2 invitation retry integration", () => {
 beforeAll(() => { sql = getSql();  process.env.CONTACT_WORKER_FORM2_ENABLED = "true"; process.env.CONTACT_TOKEN_ENCRYPTION_KEY = Buffer.alloc(32, 9).toString("base64"); process.env.FORM2_BASE_URL = "https://forms.example.test/discovery"; process.env.RESEND_API_KEY = "test"; process.env.CONTACT_RESEND_FROM = "Studio <studio@example.test>"; });
 beforeEach(async () => { send.mockReset(); send.mockResolvedValue({ data: { id: "mail" }, error: null }); await sql`TRUNCATE workflow_jobs, form2_invites, lead_identities, enquiries, leads CASCADE`; await sql`INSERT INTO leads (id, display_name, first_name, last_name) VALUES (${leadId}::uuid, 'Asha Menon', 'Asha', 'Menon')`; await sql`INSERT INTO enquiries (id, submission_id, payload_digest, lead_id, resolution_state, conflicting_lead_ids, normalized_full_name, first_name, last_name, normalized_email, normalized_phone, normalized_enquiry, privacy_notice_version, raw_purge_after) VALUES (${enquiryId}::uuid, '70000000-0000-4000-8000-000000000001'::uuid, 'digest', ${leadId}::uuid, 'resolved', ARRAY[]::uuid[], 'Asha Menon', 'Asha', 'Menon', 'asha@example.test', '+919876543210', 'A detailed enquiry for a studio project.', 'v1', now() + interval '1 day')`; });
 it("reuses the active encrypted verifier and stable provider idempotency key", async () => { await sendForm2Invitation(enquiryId, leadId); const firstUrl = String(send.mock.calls[0][0].text); await sendForm2Invitation(enquiryId, leadId); expect(send).toHaveBeenCalledTimes(2); expect(send.mock.calls[1][0].text).toBe(firstUrl); expect(send.mock.calls.map((call) => call[1])).toEqual([{ idempotencyKey: `contact/${enquiryId}/form2-invite/v1` }, { idempotencyKey: `contact/${enquiryId}/form2-invite/v1` }]); const rows = await sql<{ invites: number; encrypted: boolean }[]>`SELECT count(*)::int AS invites, bool_and(encrypted_verifier <> '') AS encrypted FROM form2_invites`; expect(rows[0]).toEqual({ invites: 1, encrypted: true }); });
});
